server:
  port: 9001

spring:
  h2:
    console:
      enabled: true
      path: /h2-ui
      
  datasource:
    url: jdbc:h2:mem:suburb_db
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      